### PR TITLE
Fixed issue with loading all-zero sparse matrices, as the data and ir…

### PR DESCRIPTION
**Pull request by SebastiaanBreedveld**
… pointers are not stored in the .mat file.

### CODE REVIEW

**Comment by skjerns** [comment]
perfect! 

bonus: could you provide a sample file for this case and write a test in  https://github.com/skjerns/mat7.3/blob/master/tests/test_mat73.py ?

alternatively, you can just send me a sample file or some script to create a sample file in MATLAB and I can add that later.

**Comment by SebastiaanBreedveld** [comment]
Sorry, I understand the importance of unit tests, but this is time-wise beyond my reach for now. I also have not used this package directly but this issue caused a problem with another script.

It should be reproducible by using the following Matlab code:
A = sparse([0 0 0; 0 0 0]);
save -v7.3 testSparse.mat A

**Comment by skjerns** [comment]
sure, no worries! the MATLAB code is enough for me to implement it :)

**Comment by skjerns** [comment]
thanks @SebastiaanBreedveld

**Pull request merged**
