### PR TITLE
Fix sparse bug #51

### PR DESCRIPTION
**Pull request by FelixBenning**
This would probably be a solution, but I am not sure, the elif case below might have to be moved to the top level too

### CODE REVIEW

**Comment by skjerns** [comment]
Thanks! The tests are passing, so it might work I guess? I'll see if I can find some way to test it thoroughly.

Does this solve #51 ?

**Comment by FelixBenning** [comment]
It would solve my issue (#52) I think based on the debugging I have done and that threw the same error.

**Comment by hernot** [comment]
> Thanks! The tests are passing, so it might work I guess? I'll see if I can find some way to test it thoroughly.
> 
> Does this solve #51 ?

From reading the committed codes, without testing, i assume yes. At least everything is plausible.

**Comment by skjerns** [comment]
thanks! that seems to have no side effects :)

**Pull request merged**
